name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      # Match the hosted runner uid:gid so checkout/file-commands can write /__w/_temp/*
      options: --user 1001:121

    env:
      # Put opam root and caches inside the workspace (writable by 1001)
      OPAMROOT: ${{ github.workspace }}/.opam-root
      HOME: ${{ github.workspace }}
      # Pin the compiler we want for the local switch
      OCAML_COMPILER: ocaml-base-compiler.5.3.0

    steps:
      - uses: actions/checkout@v4

      - name: Cache opam & dune
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.OPAMROOT }}
            ${{ github.workspace }}/_opam              # local switch (created below)
            ${{ github.workspace }}/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Prepare dirs
        run: |
          set -euxo pipefail
          mkdir -p "$OPAMROOT" "$GITHUB_WORKSPACE/.cache/dune"

      - name: Init opam root (idempotent)
        run: |
          set -euxo pipefail
          # If cache restored a non-root directory, nuke and re-init
          if [ -d "$OPAMROOT" ] && [ ! -f "$OPAMROOT/config" ]; then
            rm -rf "$OPAMROOT"
          fi
          # Initialize the custom root (no shell setup; disable sandboxing in CI)
          opam init --bare --no-setup --disable-sandboxing -y
          # Ensure default repo URL is set (harmless if already correct)
          opam repository set-url default https://opam.ocaml.org -y || true
          opam --version

      - name: Create/ensure local switch
        run: |
          set -euxo pipefail
          # Create a local switch in the repo dir if absent
          if ! opam switch show 2>/dev/null | grep -Fxq "$GITHUB_WORKSPACE"; then
            opam switch create . "$OCAML_COMPILER" -y
          fi
          opam switch list

      - name: Install deps
        run: |
          set -euxo pipefail
          opam install . --deps-only -y --switch=.

      - name: Build
        run: |
          set -euxo pipefail
          opam exec --switch=. -- dune build @install

      - name: Lint
        run: |
          set -euxo pipefail
          opam exec --switch=. -- opam lint *.opam
