name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      options: --user 1001:121

    env:
      OPAMROOT: ${{ github.workspace }}/.opam-root
      HOME: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache opam & dune
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.OPAMROOT }}
            ${{ github.workspace }}/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Init local cache dirs
        run: |
          mkdir -p "$OPAMROOT"
          mkdir -p "$GITHUB_WORKSPACE/.cache/dune"

      - name: Install deps
        run: opam install . --deps-only -y

      - name: Build
        run: opam exec -- dune build @install

      - name: Lint
        run: opam exec -- opam lint *.opam
