name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      options: --user 0:0

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install APT prerequisites
        run: |
          set -euo pipefail
          apt-get update
          apt-get install -y --no-install-recommends \
            pkg-config libgmp-dev ca-certificates git curl build-essential
          rm -rf /var/lib/apt/lists/*

      - name: Fix workspace ownership for opam user
        run: |
          set -euo pipefail
          chown -R opam:opam "$GITHUB_WORKSPACE" || true

      - name: Cache opam & dune
        uses: actions/cache@v4
        with:
          path: |
            /home/opam/.opam
            /home/opam/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-
      
      - name: Ensure switch & dune
        run: |
          su - opam -c '
            set -e
            opam update -y
            # Ensure a usable switch (the opam image usually has one, but this is safe)
            opam switch show >/dev/null 2>&1 || opam switch create default ocaml-base-compiler.5.3.0 -y
            # Make sure dune (the build tool) is installed
            opam install -y dune
          '

      - name: Install deps
        run: su - opam -c 'opam install . --deps-only -y'

      - name: Build
        run: su - opam -c 'opam exec -- dune build @install'

      - name: Lint
        run: su - opam -c 'opam exec -- opam lint *.opam'
