name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      options: --user 0:0   # run container as root so checkout can write to /__w/_temp
    steps:
      - uses: actions/checkout@v4

      # Make workspace and temp dirs writable by 'opam'
      - name: Fix permissions for opam user
        run: |
          chown -R opam:opam "$GITHUB_WORKSPACE" /__w/_temp /github/home || true

      # (Optional) cache opam/dune between runs
      - name: Cache opam
        uses: actions/cache@v4
        with:
          path: |
            /home/opam/.opam
            /home/opam/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Install deps
        run: su - opam -c 'opam install . --deps-only -y'

      - name: Build
        run: su - opam -c 'opam exec -- dune build @install'

      - name: Lint
        run: su - opam -c 'opam exec -- opam lint *.opam'
