name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      options: --user=opam   # match the image's non-root user
    steps:
      - uses: actions/checkout@v4

      # Install deps (dune will already be present in the image, but keep this)
      - name: Install deps
        run: opam install . --deps-only -y

      - name: Build
        run: opam exec -- dune build @install

      - name: Lint opam files
        run: opam exec -- opam lint *.opam
