name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      # options: --user 0:0   # ❌ remove this

    steps:
      - uses: actions/checkout@v4
      - name: Cache opam
        uses: actions/cache@v4
        with:
          path: |
            /home/opam/.opam
            /home/opam/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Install deps
        run: opam install . --deps-only -y

      - name: Build
        run: opam exec -- dune build @install

      - name: Lint
        run: opam exec -- opam lint *.opam
