name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
      options: --user 0:0   # root for apt + checkout

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install APT prerequisites
        run: |
          set -euo pipefail
          apt-get update
          apt-get install -y --no-install-recommends \
            pkg-config libgmp-dev ca-certificates git curl build-essential
          rm -rf /var/lib/apt/lists/*

      # If you want workspace owned by opam for writes, limit chown to workspace only
      - name: Fix workspace ownership for opam user
        run: |
          set -euo pipefail
          chown -R opam:opam "$GITHUB_WORKSPACE" || true

      - name: Cache opam & dune
        uses: actions/cache@v4
        with:
          path: |
            /home/opam/.opam
            /home/opam/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Install deps
        run: su - opam -c 'opam install . --deps-only -y'

      - name: Build
        run: su - opam -c 'opam exec -- dune build @install'

      - name: Lint
        run: su - opam -c 'opam exec -- opam lint *.opam'
