name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-12-ocaml-5.3
    steps:
      - uses: actions/checkout@v4

      # Make the workspace writable by 'opam'
      - name: Fix workspace permissions
        run: chown -R opam:opam /__w

      # (Optional) cache
      - name: Cache opam
        uses: actions/cache@v4
        with:
          path: |
            /home/opam/.opam
            /home/opam/.cache/dune
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Install deps
        run: su - opam -c 'opam install . --deps-only -y'

      - name: Build
        run: su - opam -c 'opam exec -- dune build @install'

      - name: Lint
        run: su - opam -c 'opam exec -- opam lint *.opam'
